// Fetch All Contacts
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';

// Get One Contact
export const GET_CONTACT = 'GET_CONTACT';

// Add Contact
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';

// Edit Contact
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAILURE = 'EDIT_CONTACT_FAILURE';

// Delete Contact
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';

export const DELETE_ALL = 'DELETE_ALL';
export const DELETE_ALL_SUCCESS = 'DELETE_ALL_SUCCESS';
export const DELETE_ALL_FAILURE = 'DELETE_ALL_FAILURE';

export const LOADING_CONTACTS = 'LOADING_CONTACTS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const EMPTY_FORM_ERROR = 'EMPTY_FORM_ERROR';
